project:
  type: website

website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: slides/slides.ipynb
        text: slides

format:
  html:
    theme: cosmo
    toc: true



